services:
    postgres:
        image: postgres:16
        container_name: ${DATABASE_NAME}
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        ports:
            - "${DATABASE_PORT}:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${DATABASE_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "5050:80"
        depends_on:
            - postgres

volumes:
    pgdata:
